BOARD := BOARD_PCA10001

C_SOURCE_FILES += adc.c
C_SOURCE_FILES += led.c
C_SOURCE_FILES += main.c
C_SOURCE_FILES += motor.c
C_SOURCE_FILES += rtc.c
C_SOURCE_FILES += user_alarm.c
C_SOURCE_FILES += acc_driver.c
C_SOURCE_FILES += app_button.c
C_SOURCE_FILES += app_fifo.c
C_SOURCE_FILES += app_gpiote.c
C_SOURCE_FILES += app_scheduler.c
C_SOURCE_FILES += app_timer.c
C_SOURCE_FILES += app_uart.c
C_SOURCE_FILES += ble_advdata.c
C_SOURCE_FILES += ble_bondmngr.c
C_SOURCE_FILES += ble_conn_params.c
C_SOURCE_FILES += ble_dtm.c
C_SOURCE_FILES += ble_flash.c
C_SOURCE_FILES += ble_racp.c
C_SOURCE_FILES += ble_radio_notification.c
C_SOURCE_FILES += ble_sensorsim.c
C_SOURCE_FILES += ble_ans_c.c
C_SOURCE_FILES += ble_as.c
C_SOURCE_FILES += ble_bas.c
C_SOURCE_FILES += ble_bps.c
C_SOURCE_FILES += ble_cscs.c
C_SOURCE_FILES += ble_dis.c
C_SOURCE_FILES += ble_gls.c
C_SOURCE_FILES += ble_gls_db.c
C_SOURCE_FILES += ble_hids.c
C_SOURCE_FILES += ble_hrs.c
C_SOURCE_FILES += ble_hts.c
C_SOURCE_FILES += ble_ias.c
C_SOURCE_FILES += ble_ias_c.c
C_SOURCE_FILES += ble_lls.c
C_SOURCE_FILES += ble_oto.c
C_SOURCE_FILES += ble_rscs.c
C_SOURCE_FILES += ble_srv_common.c
C_SOURCE_FILES += ble_tps.c
C_SOURCE_FILES += ble_stack_handler.c
C_SOURCE_FILES += dac_driver.c
C_SOURCE_FILES += pulse.c
C_SOURCE_FILES += kiss_fft.c
C_SOURCE_FILES += kiss_fftr.c
C_SOURCE_FILES += nrf_assert.c
C_SOURCE_FILES += nrf_delay.c
C_SOURCE_FILES += nrf_ecb.c
C_SOURCE_FILES += nrf_nvmc.c
C_SOURCE_FILES += simple_uart.c
C_SOURCE_FILES += spi_master.c
C_SOURCE_FILES += step_counter.c
C_SOURCE_FILES += moving_avg.c
C_SOURCE_FILES += util.c


OUTPUT_FILENAME := otolith_gcc
SDK_PATH = ../../../../../

#Uncomment correct line if you have softdevice programmed on the chip.
USE_SOFTDEVICE := S110
#USE_SOFTDEVICE := S210
	
include $(SDK_PATH)Source/templates/gcc/Makefile.common